services:
  api:
    build: .
    container_name: pmi-calculator-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MODEL_PATH=Notebook/model.knn
      - MONGODB_URI=mongodb+srv://benchmark:PMIUpload@pmi-upload.uvwlyon.mongodb.net/?retryWrites=true&w=majority&appName=PMI-Upload
    restart: always

  web:
    build: .
    container_name: pmi-calculator-website
    ports:
      - "8080:8080"
    environment:
      - WEBSITE_PORT=8080
      - API_URL=http://api:3000
      - FLASK_APP=website.website:app
    working_dir: /
    command: ["flask", "run", "--host=0.0.0.0", "--port=8080"]
    depends_on:
      - api
    restart: always

  proxy:
    image: nginx:latest
    ports:
      - "8000:80"
      - "8080:443"
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    depends_on:
      - api
      - web
